/*! PhotoSwipe - v4.0.1 - 2014-12-16
* http://photoswipe.com
* Copyright (c) 2014 Dmitry Semenov; */

/*! PhotoSwipe Default UI - 4.0.1 - 2014-12-16
* http://photoswipe.com
* Copyright (c) 2014 Dmitry Semenov; */
/**
*
* UI on top of main sliding area (caption, arrows, close button, etc.).
* Built just using public methods/properties of PhotoSwipe.
* 
*/

/* 	JIGphotoSwipe(); jQuery wrapper made exclusively for JIG by Firsh
 		Additional changes to original PhotoSwipe:
			photoswipe-ui-default.js
				_updateShareURLs
			photoswipe.js - affected functions:
				History
					_parseItemIndexFromURL
					_updateHash
					publicMethods:
						initHistory
						onHashChange
*/
(function(d,f){"function"===typeof define&&define.amd?define(f):"object"===typeof exports?module.exports=f:d.PhotoSwipe=f()})(this,function(){return function(d,f,p,oa){var g={features:null,bind:function(a,b,e,m){m=(m?"remove":"add")+"EventListener";b=b.split(" ");for(var c=0;c<b.length;c++)if(b[c])a[m](b[c],e,!1)},isArray:function(a){return a instanceof Array},createEl:function(a,b){var e=document.createElement(b||"div");a&&(e.className=a);return e},getScrollY:function(){var a=window.pageYOffset;
return void 0!==a?a:document.documentElement.scrollTop},unbind:function(a,b,e){g.bind(a,b,e,!0)},removeClass:function(a,b){a.className=a.className.replace(new RegExp("(\\s|^)"+b+"(\\s|$)")," ").replace(/^\s\s*/,"").replace(/\s\s*$/,"")},addClass:function(a,b){g.hasClass(a,b)||(a.className+=(a.className?" ":"")+b)},hasClass:function(a,b){return a.className&&(new RegExp("(^|\\s)"+b+"(\\s|$)")).test(a.className)},arraySearch:function(a,b,e){for(var m=a.length;m--;)if(a[m][e]===b)return m;return-1},extend:function(a,
b,e){for(var m in b)!b.hasOwnProperty(m)||e&&a.hasOwnProperty(m)||(a[m]=b[m])},easing:{sine:{out:function(a){return Math.sin(Math.PI/2*a)},inOut:function(a){return-(Math.cos(Math.PI*a)-1)/2}},cubic:{out:function(a){return--a*a*a+1}}},detectFeatures:function(){if(g.features)return g.features;var a=g.createEl().style,b="",e={};e.oldIE=document.all&&!document.addEventListener;e.touch="ontouchstart"in window;window.requestAnimationFrame&&(e.raf=window.requestAnimationFrame,e.caf=window.cancelAnimationFrame);
e.pointerEvent=navigator.pointerEnabled||navigator.msPointerEnabled;if(!e.pointerEvent){b=navigator.userAgent;if(/iP(hone|od)/.test(navigator.platform)){var m=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);m&&0<m.length&&(m=parseInt(m[1],10),1<=m&&8>m&&(e.isOldIOSPhone=!0))}m=(m=b.match(/Android\s([0-9\.]*)/))?m[1]:0;m=parseFloat(m);1<=m&&(4.4>m&&(e.isOldAndroid=!0),e.androidVersion=m);e.isMobileOpera=/opera mini|opera mobi/i.test(b)}for(var m=["transform","perspective","animationName"],c=["",
"webkit","Moz","ms","O"],d,k,f=0;4>f;f++){for(var b=c[f],h=0;3>h;h++)d=m[h],k=b+(b?d.charAt(0).toUpperCase()+d.slice(1):d),!e[d]&&k in a&&(e[d]=k);b&&!e.raf&&(b=b.toLowerCase(),e.raf=window[b+"RequestAnimationFrame"],e.raf&&(e.caf=window[b+"CancelAnimationFrame"]||window[b+"CancelRequestAnimationFrame"]))}if(!e.raf){var l=0;e.raf=function(a){var b=(new Date).getTime(),e=Math.max(0,16-(b-l)),m=window.setTimeout(function(){a(b+e)},e);l=b+e;return m};e.caf=function(a){clearTimeout(a)}}e.svg=!!document.createElementNS&&
!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect;return g.features=e}};g.detectFeatures();g.features.oldIE&&(g.bind=function(a,b,e,m){b=b.split(" ");for(var c=(m?"detach":"attach")+"Event",d,k=function(){e.handleEvent.call(e)},g=0;g<b.length;g++)if(d=b[g])if("object"===typeof e&&e.handleEvent){if(!m)e["oldIE"+d]=k;else if(!e["oldIE"+d])return!1;a[c]("on"+d,e["oldIE"+d])}else a[c]("on"+d,e)});var c=this,h={allowPanToNext:!0,spacing:.12,bgOpacity:1,mouseUsed:!1,loop:!0,pinchToClose:!0,
closeOnScroll:!0,closeOnVerticalDrag:!0,hideAnimationDuration:333,showAnimationDuration:333,showHideOpacity:!1,focus:!0,escKey:!0,arrowKeys:!0,mainScrollEndFriction:.35,panEndFriction:.35,scaleMode:"fit",modal:!0,alwaysFadeIn:!1};g.extend(h,oa);var y=function(){return{x:0,y:0}},v,ea,R,l,J,A,M=0,u=y(),aa=y(),n=y(),fa=y(),S,ga,z,F={},q,T,ha,ia,pa,N=0,qa=0,B=y(),ja,k,C,O=0,ab,bb,Ja,cb,Ba,ra,db=!0,U,sb=[],eb,tb,Qb,Ka,ub,La,w,Ma={},fb=function(a,b){g.extend(c,b.publicMethods);sb.push(a)},vb=function(a){var b=
P();return a>b-1?a-b:0>a?b+a:a},Na={},x=function(a,b){Na[a]||(Na[a]=[]);return Na[a].push(b)},t=function(a){var b=Na[a];if(b){var e=Array.prototype.slice.call(arguments);e.shift();for(var m=0;m<b.length;m++)b[m].apply(c,e)}},V=function(){return(new Date).getTime()},ba=function(a){gb=a;c.bg.style.opacity=a*h.bgOpacity},G=function(){W&&(W[Ba]=ha+n.x+"px, "+n.y+"px"+ia+" scale("+q+")")},Oa=function(a){a.container.style[Ba]=ha+a.initialPosition.x+"px, "+a.initialPosition.y+"px"+ia+" scale("+a.initialZoomLevel+
")"},Ca=function(a,b){b[Ba]=ha+a+"px, 0px"+ia},hb=function(a,b){if(!h.loop&&b){var e=l+(B.x*N-a)/B.x,m=Math.round(a-ka.x);if(0>e&&0<m||e>=P()-1&&0>m)a=ka.x+m*h.mainScrollEndFriction}ka.x=a;Ca(a,J)},wb=function(a,b){var e=Pa[a]-Rb[a];return aa[a]+u[a]+e-b/T*e},hc=function(a,b){return 25>Math.abs(a.x-b.x)&&25>Math.abs(a.y-b.y)},H=function(a,b){a.x=b.x;a.y=b.y;b.id&&(a.id=b.id)},xb=null,yb=function(){xb&&(g.unbind(document,"mousemove",yb),g.addClass(d,"pswp--has_mouse"),h.mouseUsed=!0,t("mouseUsed"));
xb=setTimeout(function(){xb=null},100)},zb=function(a,b){var e=ib(c.currItem,F,a);b&&(r=e);return e},Sb=function(a,b,e,m){if(m===c.currItem.initialZoomLevel)return e[a]=c.currItem.initialPosition[a],!0;e[a]=wb(a,m);return e[a]>b.min[a]?(e[a]=b.min[a],!0):e[a]<b.max[a]?(e[a]=b.max[a],!0):!1},K={},Qa=0,Ra=function(a){K[a]&&(K[a].raf&&tb(K[a].raf),Qa--,delete K[a])},Ab=function(a){K[a]&&Ra(a);K[a]||(Qa++,K[a]={})},Sa=function(){for(var a in K)K.hasOwnProperty(a)&&Ra(a)},Ta=function(a,b,e,m,c,d,k){var g=
V(),f;Ab(a);var h=function(){K[a]&&(f=V()-g,f>=m?(Ra(a),d(e),k&&k()):(d((e-b)*c(f/m)+b),K[a].raf=eb(h)))};h()},sa,Tb=function(a,b,e,m){sa&&clearTimeout(sa);Bb=Da=!0;var c;a.initialLayout?(c=a.initialLayout,a.initialLayout=null):c=h.getThumbBoundsFn&&h.getThumbBoundsFn(l);var k=function(){Ra("initialZoom");e||(ba(1),b&&(b.style.display="block"),g.addClass(d,"pswp--animated-in"),t("initialZoom"+(e?"OutEnd":"InEnd")));m&&m();Da=!1},f=e?h.hideAnimationDuration:h.showAnimationDuration;if(!c||void 0===
c.x||!f)return t("initialZoom"+(e?"Out":"In")),q=a.initialZoomLevel,H(n,a.initialPosition),G(),d.style.opacity=e?0:1,ba(1),k(),!1;a.miniImg&&(a.miniImg.style.webkitBackfaceVisibility="hidden");e||(q=c.w/a.w,n.x=c.x,n.y=c.y-Ka,h.showHideOpacity&&(d.style.opacity=.001,d.style.webkitBackfaceVisibility="hidden"),G());Ab("initialZoom");e&&!R&&g.removeClass(d,"pswp--animated-in");sa=setTimeout(function(){t("initialZoom"+(e?"Out":"In"));if(e){var b=c.w/a.w,m=n.x,l=n.y,p=q,C=Ka,v=gb,r=function(a){ja&&(C=
g.getScrollY(),ja=!1);1===a?(q=b,n.x=c.x,n.y=c.y-C,R&&k()):(q=(b-p)*a+p,n.x=(c.x-m)*a+m,n.y=(c.y-C-l)*a+l);G();h.showHideOpacity?d.style.opacity=1-a:ba(v-a*v)};R?Ta("initialZoom",0,1,f,g.easing.cubic.out,r):(r(1),sa=setTimeout(k,f+20))}else q=a.initialZoomLevel,H(n,a.initialPosition),G(),ba(1),h.showHideOpacity?d.style.opacity=1:ba(1),sa=setTimeout(k,f+20)},e?25:90);return!0},lc={shout:t,listen:x,viewportSize:F,options:h,isMainScrollAnimating:function(){return L},getZoomLevel:function(){return q},
getCurrentIndex:function(){return l},isDragging:function(){return ca},isZooming:function(){return da},applyZoomPan:function(a,b,e){n.x=b;n.y=e;q=a;G()},init:function(){if(!v&&!ea){var a;c.framework=g;c.template=d;c.bg=d.children[0];Qb=d.className;v=!0;w=g.detectFeatures();eb=w.raf;tb=w.caf;Ba=w.transform;ub=w.oldIE;c.scrollWrap=d.children[1];c.container=c.scrollWrap.children[0];J=c.container.style;Ba?(ha="translate"+(w.perspective&&!U?"3d(":"("),ia=w.perspective?", 0px)":")"):(Ba="left",g.addClass(d,
"pswp--ie"),Ca=function(a,b){b.left=a+"px"},Oa=function(a){var b=a.container.style,c=a.fitRatio*a.h;b.width=a.fitRatio*a.w+"px";b.height=c+"px";b.left=a.initialPosition.x+"px";b.top=a.initialPosition.y+"px"},G=function(){if(W){var a=W,b=c.currItem,d=b.fitRatio*b.h;a.width=b.fitRatio*b.w+"px";a.height=d+"px";a.left=n.x+"px";a.top=n.y+"px"}});a=function(a,b,c,d,k){ab=a+b;bb=a+c;Ja=a+d;cb=k?a+k:""};c.itemHolders=k=[{el:c.container.children[0],wrap:0,index:-1},{el:c.container.children[1],wrap:0,index:-1},
{el:c.container.children[2],wrap:0,index:-1}];k[0].el.style.display=k[2].el.style.display="none";(ra=w.pointerEvent)&&w.touch&&(w.touch=!1);ra?navigator.pointerEnabled?a("pointer","down","move","up","cancel"):a("MSPointer","Down","Move","Up","Cancel"):w.touch?(a("touch","start","move","end","cancel"),U=!0):a("mouse","down","move","up");S=bb+" "+Ja+" "+cb;ga=ab;ra&&!U&&(U=1<navigator.maxTouchPoints||1<navigator.msMaxTouchPoints);c.likelyTouchDevice=U;if(!w.animationName||!w.transform||w.isOldIOSPhone||
w.isOldAndroid||w.isMobileOpera)h.showAnimationDuration=h.hideAnimationDuration=0;for(a=0;a<sb.length;a++)c["init"+sb[a]]();f&&(c.ui=new f(c,g)).init();U||(h.allowPanToNext=!1);var b;z={resize:c.updateSize,scroll:function(){ja=!0;h.closeOnScroll&&v&&(!c.likelyTouchDevice||h.mouseUsed)&&2<Math.abs(g.getScrollY()-Ka)&&(R=!0,c.close())},keydown:function(a){b="";h.escKey&&27===a.keyCode?b="close":h.arrowKeys&&(37===a.keyCode?b="prev":39===a.keyCode&&(b="next"));!b||a.ctrlKey||a.altKey||a.shiftKey||a.metaKey||
(a.preventDefault?a.preventDefault():a.returnValue=!1,c[b]())}};z[ab]=ic;z[bb]=jc;z[Ja]=kc;cb&&(z[cb]=z[Ja]);w.touch&&(ga+=" mousedown",S+=" mousemove mouseup",z.mousedown=z[ab],z.mousemove=z[bb],z.mouseup=z[Ja]);t("firstUpdate");l=l||h.index||0;if(isNaN(l)||0>l||l>=P())l=0;c.currItem=ta(l);if(w.isOldIOSPhone||w.isOldAndroid)db=!1;h.modal&&(d.setAttribute("aria-hidden","false"),db?d.style.position="fixed":(d.style.position="absolute",d.style.top=g.getScrollY()+"px"));void 0===La&&(t("initialLayout"),
La=Ka=g.getScrollY());a="pswp--open ";h.mainClass&&(a+=h.mainClass+" ");h.showHideOpacity&&(a+="pswp--animate_opacity ");a+=U?"pswp--touch":"pswp--notouch";a+=w.animationName?" pswp--css_animation":"";a+=w.svg?" pswp--svg":"";g.addClass(d,a);c.updateSize();A=-1;O=null;for(a=0;3>a;a++)Ca((a+A)*B.x,k[a].el.style);ub||g.bind(c.scrollWrap,ga,c);x("initialZoomInEnd",function(){c.setContent(k[0],l-1);c.setContent(k[2],l+1);k[0].el.style.display=k[2].el.style.display="block";h.focus&&d.focus();g.bind(document,
"keydown",c);h.mouseUsed||g.bind(document,"mousemove",yb);g.bind(window,"resize scroll",c);t("bindEvents")});c.setContent(k[1],l);c.updateCurrItem();t("afterInit");db||(pa=setInterval(function(){Qa||ca||da||q!==c.currItem.initialZoomLevel||c.updateSize()},1E3));g.addClass(d,"pswp--visible")}},close:function(){v&&(v=!1,ea=!0,t("close"),g.unbind(window,"resize",c),g.unbind(window,"scroll",z.scroll),g.unbind(document,"keydown",c),g.unbind(document,"mousemove",yb),ca&&g.unbind(window,S,c),t("unbindEvents"),
Tb(c.currItem,null,!0,c.destroy))},destroy:function(){t("destroy");sa&&clearTimeout(sa);h.modal&&(d.setAttribute("aria-hidden","true"),d.className=Qb);pa&&clearInterval(pa);g.unbind(c.scrollWrap,ga,c);g.unbind(window,"scroll",c);Cb();Sa();Na=null},panTo:function(a,b,e){e||(a>r.min.x?a=r.min.x:a<r.max.x&&(a=r.max.x),b>r.min.y?b=r.min.y:b<r.max.y&&(b=r.max.y));n.x=a;n.y=b;G()},handleEvent:function(a){a=a||window.event;if(z[a.type])z[a.type](a)},goTo:function(a){a=vb(a);var b=a-l;O=b;l=a;c.currItem=
ta(l);N-=b;hb(B.x*N);Sa();L=!1;c.updateCurrItem()},next:function(){c.goTo(l+1)},prev:function(){c.goTo(l-1)},updateCurrZoomItem:function(a){a&&t("beforeChange",0);if(k[1].el.children.length){var b=k[1].el.children[0];W=g.hasClass(b,"pswp__zoom-wrap")?b.style:null}else W=null;r=c.currItem.bounds;T=q=c.currItem.initialZoomLevel;n.x=r.center.x;n.y=r.center.y;a&&t("afterChange")},invalidateCurrItems:function(){for(var a=0;3>a;a++)k[a].item&&(k[a].item.needsUpdate=!0)},updateCurrItem:function(a){if(0!==
O){var b=Math.abs(O);if(!(a&&2>b)){c.currItem=ta(l);t("beforeChange",O);3<=b&&(A+=O+(0<O?-3:3),b=3);for(var e=0;e<b;e++)0<O?(a=k.shift(),k[2]=a,A++,Ca((A+2)*B.x,a.el.style),c.setContent(a,l-b+e+1+1)):(a=k.pop(),k.unshift(a),A--,Ca(A*B.x,a.el.style),c.setContent(a,l+b-e-1-1));W&&1===Math.abs(O)&&(b=ta(C),b.initialZoomLevel!==q&&(ib(b,F),Oa(b)));O=0;c.updateCurrZoomItem();C=l;t("afterChange")}}},updateSize:function(a){if(!db){var b=g.getScrollY();La!==b&&(d.style.top=b+"px",La=b);if(!a&&Ma.x===window.innerWidth&&
Ma.y===window.innerHeight)return;Ma.x=window.innerWidth;Ma.y=window.innerHeight;d.style.height=Ma.y+"px"}F.x=c.scrollWrap.clientWidth;F.y=c.scrollWrap.clientHeight;Rb={x:0,y:La};B.x=F.x+Math.round(F.x*h.spacing);B.y=F.y;hb(B.x*N);t("beforeResize");if(void 0!==A)for(var e=0;3>e;e++)a=k[e],Ca((e+A)*B.x,a.el.style),b=ta(a.index),b.needsUpdate&&(c.cleanSlide(b),c.setContent(a,a.index),1===e&&c.updateCurrZoomItem(!0),b.needsUpdate=!1),b&&b.container&&(ib(b,F),Oa(b));T=q=c.currItem.initialZoomLevel;if(r=
c.currItem.bounds)n.x=r.center.x,n.y=r.center.y,G();t("resize")},zoomTo:function(a,b,e,c,d){b&&(T=q,Pa.x=Math.abs(b.x)-n.x,Pa.y=Math.abs(b.y)-n.y,H(aa,n));b=zb(a,!1);var k={};Sb("x",b,k,a);Sb("y",b,k,a);var f=q,h=n.x,l=n.y;b=function(b){1===b?(q=a,n.x=k.x,n.y=k.y):(q=(a-f)*b+f,n.x=(k.x-h)*b+h,n.y=(k.y-l)*b+l);d&&d(b);G()};e?Ta("customZoomTo",0,1,e,c||g.easing.sine.inOut,b):b(1)}},Ub,jb,D={},X={},E={},I={},Ea={},la=[],ua={},Ua,va=[],Db,Eb,Fb,kb,Va,ca,Gb,Fa,Wa,lb,wa,Q,da,Vb,r,ka=y(),W,L,Pa=y(),xa=y(),
ya,Rb,Hb,mb,gb,nb,Wb=function(a,b){Eb=Math.abs(a.x-b.x);Fb=Math.abs(a.y-b.y);return Math.sqrt(Eb*Eb+Fb*Fb)},Cb=function(){lb&&(tb(lb),lb=null)},Xb=function(){if(ca&&(lb=eb(Xb),Q)){var a=Q.length;if(0!==a)if(H(D,Q[0]),E.x=D.x-I.x,E.y=D.y-I.y,da&&1<a){I.x=D.x;I.y=D.y;if(a=!E.x&&!E.y)a=Q[1],a=a.x===X.x&&a.y===X.y;if(!a){H(X,Q[1]);Fa||(Fa=!0,t("zoomGestureStarted"));a=Wb(D,X);a=1/Vb*a*T;a>c.currItem.initialZoomLevel+c.currItem.initialZoomLevel/15&&(nb=!0);var b=1;a<c.currItem.minZoom?h.pinchToClose&&
!nb&&T<=c.currItem.initialZoomLevel?(b=1-(c.currItem.minZoom-a)/(c.currItem.minZoom/1.2),ba(b),t("onPinchClose",b),mb=!0):(b=(c.currItem.minZoom-a)/c.currItem.minZoom,1<b&&(b=1),a=c.currItem.minZoom-c.currItem.minZoom/3*b):a>c.currItem.maxZoom&&(b=(a-c.currItem.maxZoom)/(6*c.currItem.minZoom),1<b&&(b=1),a=c.currItem.maxZoom+b*c.currItem.minZoom);fa.x=.5*(D.x+X.x);fa.y=.5*(D.y+X.y);u.x+=fa.x-xa.x;u.y+=fa.y-xa.y;H(xa,fa);n.x=wb("x",a);n.y=wb("y",a);Db=a>q;q=a;G()}}else if(ya&&(Hb&&(Hb=!1,10<=Math.abs(E.x)&&
(E.x-=Q[0].x-Ea.x),10<=Math.abs(E.y)&&(E.y-=Q[0].y-Ea.y)),I.x=D.x,I.y=D.y,0!==E.x||0!==E.y)){if("v"===ya&&h.closeOnVerticalDrag&&"fit"===h.scaleMode&&q===c.currItem.initialZoomLevel)u.y+=E.y,n.y+=E.y,a=Yb(),kb=!0,t("onVerticalDrag",a),ba(a);else{var a=V(),b=D.x,e=D.y;if(50<a-jb){var m=2<va.length?va.shift():{};m.x=b;m.y=e;va.push(m);jb=a}Wa=!0;r=c.currItem.bounds;Zb("x",E)||Zb("y",E)}G()}}},Ib={},$b=function(a,b){Ib.prevent="A"!==a.target.tagName;t("preventDragEvent",a,b,Ib);return Ib.prevent},ac=
function(a,b){b.x=a.pageX;b.y=a.pageY;b.id=a.identifier;return b},Yb=function(){return 1-Math.abs((n.y-c.currItem.initialPosition.y)/(F.y/2))},Xa={},mc={},ma=[],ob,Jb=function(a){for(;0<ma.length;)ma.pop();ra?(ob=0,la.forEach(function(a){0===ob?ma[0]=a:1===ob&&(ma[1]=a);ob++})):-1<a.type.indexOf("touch")?a.touches&&0<a.touches.length&&(ma[0]=ac(a.touches[0],Xa),1<a.touches.length&&(ma[1]=ac(a.touches[1],mc))):(Xa.x=a.pageX,Xa.y=a.pageY,Xa.id="",ma[0]=Xa);return ma},Zb=function(a,b){var e,m=n[a]+b[a],
d,k=0<b[a],g=ka.x+b.x,f=ka.x-ua.x;e=m>r.min[a]||m<r.max[a]?h.panEndFriction:1;var m=n[a]+b[a]*e,l,C;if(h.allowPanToNext||q===c.currItem.initialZoomLevel)if(W?"h"!==ya||"x"!==a||Fa||(k?(m>r.min[a]&&(e=h.panEndFriction,d=r.min[a]-aa[a]),(0>=d||0>f)&&1<P()?(C=g,0>f&&g>ua.x&&(C=ua.x)):r.min.x!==r.max.x&&(l=m)):(m<r.max[a]&&(e=h.panEndFriction,d=aa[a]-r.max[a]),(0>=d||0<f)&&1<P()?(C=g,0<f&&g<ua.x&&(C=ua.x)):r.min.x!==r.max.x&&(l=m))):C=g,"x"===a)return void 0!==C&&(hb(C,!0),wa=C===ua.x?!1:!0),r.min.x!==
r.max.x&&(void 0!==l?n.x=l:wa||(n.x+=b.x*e)),void 0!==C;L||wa||q>c.currItem.fitRatio&&(n[a]+=b[a]*e)},ic=function(a){if(Da)a.preventDefault();else if(!Va||"mousedown"!==a.type){$b(a,!0)&&a.preventDefault();t("pointerDown");if(ra){var b=g.arraySearch(la,a.pointerId,"id");0>b&&(b=la.length);la[b]={x:a.pageX,y:a.pageY,id:a.pointerId}}a=Jb(a);b=a.length;Q=null;Sa();ca&&1!==b||(ca=Hb=!0,g.bind(window,S,c),Db=nb=mb=kb=wa=Wa=Gb=Fa=!1,ya=null,t("firstTouchStart",a),H(aa,n),u.x=u.y=0,H(I,a[0]),H(Ea,I),ua.x=
B.x*N,va=[{x:I.x,y:I.y}],jb=Ub=V(),zb(q,!0),Cb(),Xb());!da&&1<b&&!L&&!wa&&(T=q,Fa=!1,da=Gb=!0,u.y=u.x=0,H(aa,n),H(D,a[0]),H(X,a[1]),xa.x=.5*(D.x+X.x),xa.y=.5*(D.y+X.y),Pa.x=Math.abs(xa.x)-n.x,Pa.y=Math.abs(xa.y)-n.y,Vb=Wb(D,X))}},jc=function(a){a.preventDefault();if(ra){var b=g.arraySearch(la,a.pointerId,"id");-1<b&&(b=la[b],b.x=a.pageX,b.y=a.pageY)}ca&&(a=Jb(a),ya||Wa||da?Q=a:(b=Math.abs(a[0].x-I.x)-Math.abs(a[0].y-I.y),10<=Math.abs(b)&&(ya=0<b?"h":"v",Q=a)))},kc=function(a){if(w.isOldAndroid){if(Va&&
"mouseup"===a.type)return;-1<a.type.indexOf("touch")&&(clearTimeout(Va),Va=setTimeout(function(){Va=0},600))}t("pointerUp");$b(a,!1)&&a.preventDefault();var b;if(ra){var e=g.arraySearch(la,a.pointerId,"id");-1<e&&(b=la.splice(e,1)[0],navigator.pointerEnabled?b.type=a.pointerType||"mouse":(b.type={4:"mouse",2:"touch",3:"pen"}[a.pointerType],b.type||(b.type=a.pointerType||"mouse")))}var m=Jb(a),e=m.length;"mouseup"===a.type&&(e=0);if(2===e)return Q=null,!0;1===e&&H(Ea,m[0]);0!==e||ya||L||(b||("mouseup"===
a.type?b={x:a.pageX,y:a.pageY,type:"mouse"}:a.changedTouches&&a.changedTouches[0]&&(b={x:a.changedTouches[0].pageX,y:a.changedTouches[0].pageY,type:"touch"})),t("touchRelease",a,b));a=-1;0===e&&(ca=!1,g.unbind(window,S,c),Cb(),da?a=0:-1!==M&&(a=V()-M));M=1===e?V():-1;a=-1!==a&&150>a?"zoom":"swipe";da&&2>e&&(da=!1,1===e&&(a="zoomPointerUp"),t("zoomGestureEnded"));Q=null;if(Wa||Fa||L||kb)if(Sa(),Ua||(Ua=nc()),Ua.calculateSwipeSpeed("x"),kb)if(.6>Yb())c.close();else{var d=n.y,k=gb;Ta("verticalDrag",
0,1,300,g.easing.cubic.out,function(a){n.y=(c.currItem.initialPosition.y-d)*a+d;ba((1-k)*a+k);G()});t("onVerticalDrag",1)}else{if((wa||L)&&0===e){if(oc(a,Ua))return;a="zoomPointerUp"}L||("swipe"!==a?pc():!wa&&q>c.currItem.fitRatio&&qc(Ua))}},nc=function(){var a,b,e={lastFlickOffset:{},lastFlickDist:{},lastFlickSpeed:{},slowDownRatio:{},slowDownRatioReverse:{},speedDecelerationRatio:{},speedDecelerationRatioAbs:{},distanceOffset:{},backAnimDestination:{},backAnimStarted:{},calculateSwipeSpeed:function(c){1<
va.length?(a=V()-jb+50,b=va[va.length-2][c]):(a=V()-Ub,b=Ea[c]);e.lastFlickOffset[c]=I[c]-b;e.lastFlickDist[c]=Math.abs(e.lastFlickOffset[c]);e.lastFlickSpeed[c]=20<e.lastFlickDist[c]?e.lastFlickOffset[c]/a:0;.1>Math.abs(e.lastFlickSpeed[c])&&(e.lastFlickSpeed[c]=0);e.slowDownRatio[c]=.95;e.slowDownRatioReverse[c]=1-e.slowDownRatio[c];e.speedDecelerationRatio[c]=1},calculateOverBoundsAnimOffset:function(a,b){e.backAnimStarted[a]||(n[a]>r.min[a]?e.backAnimDestination[a]=r.min[a]:n[a]<r.max[a]&&(e.backAnimDestination[a]=
r.max[a]),void 0!==e.backAnimDestination[a]&&(e.slowDownRatio[a]=.7,e.slowDownRatioReverse[a]=1-e.slowDownRatio[a],.05>e.speedDecelerationRatioAbs[a]&&(e.lastFlickSpeed[a]=0,e.backAnimStarted[a]=!0,Ta("bounceZoomPan"+a,n[a],e.backAnimDestination[a],b||300,g.easing.sine.out,function(b){n[a]=b;G()}))))},calculateAnimOffset:function(a){e.backAnimStarted[a]||(e.speedDecelerationRatio[a]*=e.slowDownRatio[a]+e.slowDownRatioReverse[a]-e.slowDownRatioReverse[a]*e.timeDiff/10,e.speedDecelerationRatioAbs[a]=
Math.abs(e.lastFlickSpeed[a]*e.speedDecelerationRatio[a]),e.distanceOffset[a]=e.lastFlickSpeed[a]*e.speedDecelerationRatio[a]*e.timeDiff,n[a]+=e.distanceOffset[a])},panAnimLoop:function(){K.zoomPan&&(K.zoomPan.raf=eb(e.panAnimLoop),e.now=V(),e.timeDiff=e.now-e.lastNow,e.lastNow=e.now,e.calculateAnimOffset("x"),e.calculateAnimOffset("y"),G(),e.calculateOverBoundsAnimOffset("x"),e.calculateOverBoundsAnimOffset("y"),.05>e.speedDecelerationRatioAbs.x&&.05>e.speedDecelerationRatioAbs.y&&Ra("zoomPan"))}};
return e},qc=function(a){a.calculateSwipeSpeed("y");r=c.currItem.bounds;a.backAnimDestination={};a.backAnimStarted={};if(.05>=Math.abs(a.lastFlickSpeed.x)&&.05>=Math.abs(a.lastFlickSpeed.y))return a.speedDecelerationRatioAbs.x=a.speedDecelerationRatioAbs.y=0,a.calculateOverBoundsAnimOffset("x"),a.calculateOverBoundsAnimOffset("y"),!0;Ab("zoomPan");a.lastNow=V();a.panAnimLoop()},oc=function(a,b){var e;L||(qa=l);var d;if("swipe"===a){var k=I.x-Ea.x;30<k&&(10>b.lastFlickDist.x||20<b.lastFlickOffset.x)?
d=-1:-30>k&&(10>b.lastFlickDist.x||-20>b.lastFlickOffset.x)&&(d=1)}var f;d&&(l+=d,0>l?(l=h.loop?P()-1:0,f=!0):l>=P()&&(l=h.loop?0:P()-1,f=!0),!f||h.loop)&&(O+=d,N-=d,e=!0);d=B.x*N;k=Math.abs(d-ka.x);e||d>ka.x===0<b.lastFlickSpeed.x?(k=0<Math.abs(b.lastFlickSpeed.x)?k/Math.abs(b.lastFlickSpeed.x):333,k=Math.min(k,400),k=Math.max(k,250)):k=333;qa===l&&(e=!1);L=!0;Ta("mainScroll",ka.x,d,k,g.easing.cubic.out,hb,function(){Sa();L=!1;qa=-1;(e||qa!==l)&&c.updateCurrItem();t("mainScrollAnimComplete")});e&&
c.updateCurrItem(!0);return e},pc=function(){var a=q;q<c.currItem.minZoom?a=c.currItem.minZoom:q>c.currItem.maxZoom&&(a=c.currItem.maxZoom);var b,e=gb;if(mb&&!Db&&!nb&&q<c.currItem.minZoom)return R=!0,c.close(),!0;mb&&(b=function(a){ba((1-e)*a+e)});c.zoomTo(a,0,300,g.easing.cubic.out,b);return!0},Ga,Ha,Ia,Ya,Za,za=[],Bb,Da,rc={index:0,errorMsg:'<div class="pswp__error-msg"><a href="%url%" target="_blank">The image</a> could not be loaded.</div>',forceProgressiveLoading:!1,preload:[1,1],getNumItemsFn:function(){return Ga.length}},
ta,P,ib=function(a,b,e){if(a.src){var c=!e;c&&(a.vGap||(a.vGap={top:0,bottom:0}),t("parseVerticalMargin",a));Ha=b.x;Ia=b.y-a.vGap.top-a.vGap.bottom;if(c){b=Ha/a.w;var d=Ia/a.h;a.fitRatio=b<d?b:d;a.fillRatio=b>d?b:d;b=h.scaleMode;"orig"===b?e=1:"fit"===b?e=a.fitRatio:"fill"===b&&(e=a.fillRatio);1<e&&(e=1);a.initialZoomLevel=e;a.maxZoom=2;a.doubleTapZoom=1<2*e?2*e:1;a.minZoom=e;a.bounds||(a.bounds={center:{},max:{},min:{}})}if(!e)return;Ya=a.w*e;Za=a.h*e;b=a.bounds;b.center.x=Math.round((Ha-Ya)/2);
b.center.y=Math.round((Ia-Za)/2)+a.vGap.top;b.max.x=Ya>Ha?Math.round(Ha-Ya):b.center.x;b.max.y=Za>Ia?Math.round(Ia-Za)+a.vGap.top:b.center.y;b.min.x=Ya>Ha?0:b.center.x;b.min.y=Za>Ia?a.vGap.top:b.center.y;c&&e===a.initialZoomLevel&&(a.initialPosition=b.center);return b}return!1},pb=function(a,b,e,d,k,f){var g;!k&&(U||h.alwaysFadeIn)&&(a===l||c.isMainScrollAnimating()||c.isDragging()&&!c.isZooming())&&(g=!0);d&&(g&&(d.style.opacity=0),b.imageAppended=!0,e.appendChild(d),g&&setTimeout(function(){d.style.opacity=
1;f&&setTimeout(function(){b&&b.loaded&&b.placeholder&&(b.placeholder.style.display="none",b.placeholder=null)},500)},50))},bc=function(a){a.loading=!0;a.loaded=!1;var b=a.img=g.createEl("pswp__img","img"),e=function(){a.loading=!1;a.loaded=!0;a.loadComplete?a.loadComplete(a):a.img=null;b=b.onload=b.onerror=null};b.onload=e;b.onerror=function(){a.loadError=!0;e()};b.src=a.src;return b},cc=function(a,b){if(a.loadError)return b.el.innerHTML=h.errorMsg.replace("%url%",a.src),!0},dc=function(){if(za.length){for(var a,
b=0;b<za.length;b++)a=za[b],a.holder.index===a.index&&pb(a.index,a.item,a.baseDiv,a.img);za=[]}};fb("Controller",{publicMethods:{lazyLoadItem:function(a){a=vb(a);var b=ta(a);!b||b.loaded||b.loading||(t("gettingData",a,b),bc(b))},initController:function(){g.extend(h,rc,!0);c.items=Ga=p;ta=c.getItemAt;P=h.getNumItemsFn;3>P()&&(h.loop=!1);x("beforeChange",function(a){var b=h.preload;a=null===a?!0:0<a;var e=Math.min(b[0],P()),b=Math.min(b[1],P()),d;for(d=1;d<=(a?b:e);d++)c.lazyLoadItem(l+d);for(d=1;d<=
(a?e:b);d++)c.lazyLoadItem(l-d)});x("initialLayout",function(){c.currItem.initialLayout=h.getThumbBoundsFn&&h.getThumbBoundsFn(l)});x("mainScrollAnimComplete",dc);x("initialZoomInEnd",dc);x("destroy",function(){for(var a,b=0;b<Ga.length;b++)a=Ga[b],a.container&&(a.container=null),a.placeholder&&(a.placeholder=null),a.img&&(a.img=null),a.preloader&&(a.preloader=null),a.loadError&&(a.loaded=a.loadError=!1);za=null})},getItemAt:function(a){return 0<=a?void 0!==Ga[a]?Ga[a]:!1:!1},allowProgressiveImg:function(){return h.forceProgressiveLoading||
!U||h.mouseUsed||1200<screen.width},setContent:function(a,b){h.loop&&(b=vb(b));var e=c.getItemAt(a.index);e&&(e.container=null);var e=c.getItemAt(b),d;if(e)if(t("gettingData",b,e),a.index=b,a.item=e,cc(e,a))e.initialPosition.x=e.initialPosition.y=0,e.initialZoomLevel=e.maxZoom=e.minZoom=1,W=null,e.w=50,e.h=50,Oa(e);else{var k=e.container=g.createEl("pswp__zoom-wrap");if(e.loaded)d=g.createEl("pswp__img","img"),d.style.webkitBackfaceVisibility="hidden",d.style.opacity=1,d.src=e.src,pb(b,e,k,d,!0);
else{e.loadComplete=function(e){if(v){e.img.style.webkitBackfaceVisibility="hidden";if(a.index===b){if(cc(e,a)){e.img=null;return}e.imageAppended?!Da&&e.placeholder&&(e.placeholder.style.display="none",e.placeholder=null):L||Da?za.push({item:e,baseDiv:k,img:e.img,index:b,holder:a}):pb(b,e,k,e.img,L||Da)}e.loadComplete=null;e.img=null;t("imageLoadComplete",b,e)}};if(g.features.transform){var f=g.createEl("pswp__img pswp__img--placeholder"+(e.msrc?"":" pswp__img--placeholder--blank"),e.msrc?"img":"");
e.msrc&&(f.src=e.msrc);f.style.width=e.w+"px";f.style.height=e.h+"px";k.appendChild(f);e.placeholder=f}e.loading||bc(e);c.allowProgressiveImg()&&(Bb?pb(b,e,k,e.img,!0,!0):za.push({item:e,baseDiv:k,img:e.img,index:b,holder:a}))}ib(e,F);Bb||b!==l?Oa(e):(W=k.style,Tb(e,d||e.img));a.el.innerHTML="";a.el.appendChild(k)}else a.el.innerHTML=""},cleanSlide:function(a){a.img&&(a.img.onload=a.img.onerror=null);a.loaded=a.loading=a.img=a.imageAppended=!1}}});var na,Kb={},Lb=function(a,b,e){var d=document.createEvent("CustomEvent");
d.initCustomEvent("pswpTap",!0,!0,{origEvent:a,target:a.target,releasePoint:b,pointerType:e||"touch"});a.target.dispatchEvent(d)};fb("Tap",{publicMethods:{initTap:function(){x("firstTouchStart",c.onTapStart);x("touchRelease",c.onTapRelease);x("destroy",function(){Kb={};na=null})},onTapStart:function(a){1<a.length&&(clearTimeout(na),na=null)},onTapRelease:function(a,b){if(b&&!Wa&&!Gb&&!Qa){if(na&&(clearTimeout(na),na=null,hc(b,Kb))){t("doubleTap",b);return}var e=a.target.tagName.toLowerCase();"mouse"===
b.type?Lb(a,b,"mouse"):"button"===e||g.hasClass(a.target,"pswp__single-tap")?Lb(a,b):(H(Kb,b),na=setTimeout(function(){Lb(a,b);na=null},300))}}}});var Y;fb("DesktopZoom",{publicMethods:{handleMouseWheel:function(a){if(q<=c.currItem.fitRatio)return!0;a.preventDefault();a.stopPropagation();Y.x=0;if("deltaX"in a)Y.x=a.deltaX,Y.y=a.deltaY;else if("wheelDelta"in a)a.wheelDeltaX&&(Y.x=-.16*a.wheelDeltaX),Y.y=a.wheelDeltaY?-.16*a.wheelDeltaY:-.16*a.wheelDelta;else if("detail"in a)Y.y=a.detail;else return;
zb(q,!0);c.panTo(n.x-Y.x,n.y-Y.y)},toggleDesktopZoom:function(a){a=a||{x:F.x/2,y:F.y/2+Ka};var b=1===q;c.mouseZoomedIn=!b;c.zoomTo(b?c.currItem.initialZoomLevel:1,a,333);g[(b?"remove":"add")+"Class"](d,"pswp--zoomed-in")},setupDesktopZoom:function(a){Y={};x("bindEvents",function(){g.bind(d,"wheel mousewheel DOMMouseScroll",c.handleMouseWheel)});x("unbindEvents",function(){Y&&g.unbind(d,"wheel mousewheel DOMMouseScroll",c.handleMouseWheel)});c.mouseZoomedIn=!1;var b,e=function(){c.mouseZoomedIn&&(g.removeClass(d,
"pswp--zoomed-in"),c.mouseZoomedIn=!1);1>q?g.addClass(d,"pswp--zoom-allowed"):g.removeClass(d,"pswp--zoom-allowed");k()},k=function(){b&&(g.removeClass(d,"pswp--dragging"),b=!1)};x("resize",e);x("afterChange",e);x("pointerDown",function(){c.mouseZoomedIn&&(b=!0,g.addClass(d,"pswp--dragging"))});x("pointerUp",k);a||e()},initDesktopZoom:function(){ub||(U?x("mouseUsed",function(){c.setupDesktopZoom()}):c.setupDesktopZoom(!0))}}});var sc={history:!0,galleryUID:1},$a,ec,Aa,qb,Mb,fc,rb,Nb,Ob,Z,gc=function(){var a=
"",b;b=Z.hash.substring(1);var e={};b=b.replace("%5B","[");b=b.replace("%5D","]");b=b.replace(/([^|])(poster=|videoplayer)/mg,"$1|$2");b=b.match(/^!([\w\-[\]]+?\/(?:(\d+)(?=\/))?(https?:\/\/[^&]*)?([A-Z]{2}\/[_\w]*)?)/im);null!==b?(a=b[1],a=a.substring(a.indexOf("/")+1,a.length),/^([A-Z]{2}\/[_\w]*)$/im.test(a)&&(a=a.replace("/","-")),jQuery.each(p,function(b,d){if("undefined"!==typeof d.contentID&&d.contentID=="jig-contentID-"+a||d.src==a)return e.pid=b,!1}),e.pid=parseInt(e.pid,10)):e.pid=0;return e},
Pb=function(){Aa&&clearTimeout(Aa);if(Qa||ca)Aa=setTimeout(Pb,500);else{qb?clearTimeout(ec):qb=!0;var a="!"+h.galleryUID+"/";if("undefined"!==typeof p[l].contentID){var b=/(?:jig-contentID)-(\w{2})-([^\s]*)/im.exec(p[l].contentID);null!==b&&(a+=b[1]+"/"+b[2])}else a+=p[l].src;rb?(a=Z.href.split("#")[0]+"#"+a,Z.replace(a)):(-1===Z.hash.indexOf(a)&&(Ob=!0),Z.hash=a);rb=!0;ec=setTimeout(function(){qb=!1},60)}};fb("History",{publicMethods:{initHistory:function(){g.extend(h,sc,!0);if(h.history){Z=window.location;
rb=Nb=Ob=!1;x("afterChange",c.updateURL);x("unbindEvents",function(){g.unbind(window,"hashchange",c.onHashChange)});var a=function(){fc=!0;Nb||(Ob?history.back():"pushState"in history?history.pushState("",document.title,Z.pathname+Z.search):Z.hash="");$a&&clearTimeout($a);Aa&&clearTimeout(Aa)};x("unbindEvents",function(){R&&a()});x("destroy",function(){fc||a()});x("firstUpdate",function(){l=gc().pid});setTimeout(function(){v&&g.bind(window,"hashchange",c.onHashChange)},40)}},onHashChange:function(){""===
Z.hash.substring(1)?(Nb=!0,c.close()):qb||(Mb=!0,c.goTo(gc().pid),Mb=!1)},updateURL:function(){$a&&clearTimeout($a);Aa&&clearTimeout(Aa);Mb||(rb?$a=setTimeout(Pb,800):Pb())}}});g.extend(c,lc)}});
(function(d,f){"function"===typeof define&&define.amd?define(f):"object"===typeof exports?module.exports=f:d.PhotoSwipeUI_Default=f()})(this,function(){return function(d,f){var p=this,oa=!1,g=!0,c,h,y,v,ea,R,l,J=!0,A,M,u,aa,n,fa={barsSize:{top:44,bottom:"auto"},closeElClasses:["item","caption","zoom-wrap","ui","top-bar"],timeToIdle:4E3,timeToIdleOutside:1E3,loadingIndicatorDelay:1E3,addCaptionHTMLFn:function(d,c){if(!d.title)return c.children[0].innerHTML="",!1;c.children[0].innerHTML=d.title;return!0},
closeEl:!0,captionEl:!0,fullscreenEl:!0,zoomEl:!0,shareEl:!0,counterEl:!0,arrowEl:!0,preloaderEl:!0,tapToClose:!1,tapToToggleControls:!0,shareButtons:[{id:"facebook",label:"Share on Facebook",url:"https://www.facebook.com/sharer/sharer.php?u={{url}}"},{id:"twitter",label:"Tweet",url:"https://twitter.com/intent/tweet?text={{text}}&url={{url}}"},{id:"pinterest",label:"Pin it",url:"http://www.pinterest.com/pin/create/button/?url={{url}}&media={{image_url}}&description={{text}}"},{id:"download",label:"Download image",
url:"{{raw_image_url}}",download:!0}],indexIndicatorSep:" / "},S,ga=function(d){if(S)return!0;d=d||window.event;for(var c,g=(d.target||d.srcElement).className,h,l=0;l<ja.length;l++)c=ja[l],c.onTap&&-1<g.indexOf("pswp__"+c.name)&&(c.onTap(),h=!0);h&&(d.stopPropagation&&d.stopPropagation(),S=!0,setTimeout(function(){S=!1},f.features.isOldAndroid?600:30))},z=function(){(J=!J)?(f.removeClass(l,"pswp__share-modal--fade-in"),setTimeout(function(){if(J)f[(J?"add":"remove")+"Class"](l,"pswp__share-modal--hidden")},
300)):(f[(J?"add":"remove")+"Class"](l,"pswp__share-modal--hidden"),setTimeout(function(){J||f.addClass(l,"pswp__share-modal--fade-in")},30));J||q();return!1},F=function(d){d=d||window.event;d=d.target||d.srcElement;if(!d.href)return!1;if(d.hasAttribute("download"))return!0;window.open(d.href,"pswp_share","scrollbars=yes,resizable=yes,toolbar=no,location=yes,width=550,height=420,top=100,left="+(window.screen?Math.round(screen.width/2-275):100));J||z();return!1},q=function(){var c="",f,g,h;location.hash?
(h=decodeURI(document.location.href),f=h.split("#!"),h=f[0]+"#!"+f[1]):h=location.href;for(var n=0;n<d.options.shareButtons.length;n++)f=d.options.shareButtons[n],g=(d.currItem.title||"")+(d.currItem.description?(d.currItem.title?" ":"")+d.currItem.description:"")||document.title,g=f.url.replace("{{url}}",encodeURIComponent(h)).replace("{{facebook_url}}",encodeURIComponent(h.replace("#!",(-1===h.indexOf("?")?"?":"&")+"_escaped_fragment_="))).replace("{{image_url}}",encodeURIComponent(d.currItem.src||
"")).replace("{{raw_image_url}}",d.currItem.src||"").replace("{{title}}",encodeURIComponent(d.currItem.title||document.title)).replace("{{description}}",encodeURIComponent(jQuery("<p>"+g.replace(/<a(?:.+?)href=['"](.+?)['"](?:.+?>)(.+?)(?:<\/a>)/mg,"$2: $1")+"</p>").text())),c+='<a href="'+g+'" target="_blank" class="pswp__share--'+f.id+'"'+(f.download?"download":"")+">"+f.label+"</a>";l.children[0].innerHTML=c;l.children[0].onclick=F},T=function(c){for(var g=0;g<d.options.closeElClasses.length;g++)if(f.hasClass(c,
"pswp__"+d.options.closeElClasses[g]))return!0},ha,ia,pa=0,N=function(){clearTimeout(ia);pa=0;M&&p.setIdle(!1)},qa=function(c){c=c?c:window.event;c=c.relatedTarget||c.toElement;c&&"HTML"!==c.nodeName||(clearTimeout(ia),ia=setTimeout(function(){p.setIdle(!0)},d.options.timeToIdleOutside))},B=function(d){aa!==d&&(f[(d?"remove":"add")+"Class"](u,"pswp__preloader--active"),aa=d)},ja=[{name:"caption",option:"captionEl",onInit:function(d){y=d}},{name:"share-modal",option:"shareEl",onInit:function(d){l=
d},onTap:function(){z()}},{name:"button--share",option:"shareEl",onInit:function(d){R=d},onTap:function(){z()}},{name:"button--zoom",option:"zoomEl",onTap:d.toggleDesktopZoom},{name:"counter",option:"counterEl",onInit:function(d){ea=d}},{name:"button--close",option:"closeEl",onTap:d.close},{name:"button--arrow--left",option:"arrowEl",onTap:d.prev},{name:"button--arrow--right",option:"arrowEl",onTap:d.next},{name:"button--fs",option:"fullscreenEl",onTap:function(){c.isFullscreen()?c.exit():c.enter()}},
{name:"preloader",option:"preloaderEl",onInit:function(d){u=d}}];p.init=function(){f.extend(d.options,fa,!0);h=d.scrollWrap.children[1];var k=d.listen;k("onVerticalDrag",function(d){g&&.95>d?p.hideControls():!g&&.95<=d&&p.showControls()});var q;k("onPinchClose",function(d){g&&.9>d?(p.hideControls(),q=!0):q&&!g&&.9<d&&p.showControls()});k("zoomGestureEnded",function(){q=!1});k("beforeChange",p.update);k("doubleTap",function(c){var f=d.currItem.initialZoomLevel;d.getZoomLevel()!==f?d.zoomTo(f,c,333):
d.zoomTo(d.currItem.doubleTapZoom,c,333)});d.options.timeToIdle&&k("mouseUsed",function(){f.bind(document,"mousemove",N);f.bind(document,"mouseout",qa);ha=setInterval(function(){pa++;2===pa&&p.setIdle(!0)},d.options.timeToIdle/2)});k("preventDragEvent",function(d,c,f){(c=d.target||d.srcElement)&&c.className&&-1<d.type.indexOf("mouse")&&(0<c.className.indexOf("__caption")||/(SMALL|STRONG|EM)/i.test(c.tagName))&&(f.prevent=!1)});k("bindEvents",function(){f.bind(h,"pswpTap click",ga);f.bind(d.scrollWrap,
"pswpTap",p.onGlobalTap);d.likelyTouchDevice||f.bind(d.scrollWrap,"mouseover",p.onMouseOver)});k("unbindEvents",function(){J||z();ha&&clearInterval(ha);f.unbind(document,"mouseout",qa);f.unbind(document,"mousemove",N);f.unbind(h,"pswpTap click",ga);f.unbind(d.scrollWrap,"pswpTap",p.onGlobalTap);f.unbind(d.scrollWrap,"mouseover",p.onMouseOver);c&&(f.unbind(document,c.eventK,p.updateFullscreen),c.isFullscreen()&&(fa.hideAnimationDuration=0,c.exit()),c=null)});k("destroy",function(){d.options.captionEl&&
(v&&h.removeChild(v),f.removeClass(y,"pswp__caption--empty"));l&&(l.children[0].onclick=null);f.removeClass(h,"pswp__ui--over-close");f.addClass(h,"pswp__ui--hidden");p.setIdle(!1)});d.options.showAnimationDuration||f.removeClass(h,"pswp__ui--hidden");k("initialZoomIn",function(){d.options.showAnimationDuration&&f.removeClass(h,"pswp__ui--hidden")});k("initialZoomOut",function(){f.addClass(h,"pswp__ui--hidden")});k("parseVerticalMargin",function(c){var k=c.vGap;if(!d.likelyTouchDevice||d.options.mouseUsed||
1200<screen.width){var g=d.options.barsSize;d.options.captionEl&&"auto"===g.bottom?(v||(v=f.createEl("pswp__caption pswp__caption--fake"),v.appendChild(f.createEl("pswp__caption__center")),h.insertBefore(v,y),f.addClass(h,"pswp__ui--fit")),d.options.addCaptionHTMLFn(c,v,!0)?k.bottom=parseInt(v.clientHeight,10)||44:k.bottom=g.top):k.bottom=g.bottom;k.top=g.top}else k.top=k.bottom=0});var u,ea,M,A=function(c){for(var k=c.length,g=0;g<k;g++){u=c[g];ea=u.className;for(var h=0;h<ja.length;h++)if(M=ja[h],
-1<ea.indexOf("pswp__"+M.name))if(d.options[M.option]){if(f.removeClass(u,"pswp__element--disabled"),M.onInit)M.onInit(u)}else f.addClass(u,"pswp__element--disabled")}};A(h.children);A(h.children[0].children);d.options.shareEl&&R&&l&&(J=!0);d.options.fullscreenEl&&(c||(c=p.getFullscreenAPI()),c?(f.bind(document,c.eventK,p.updateFullscreen),p.updateFullscreen(),f.addClass(d.template,"pswp--supports-fs")):f.removeClass(d.template,"pswp--supports-fs"));d.options.preloaderEl&&(B(!0),k("beforeChange",
function(){clearTimeout(n);n=setTimeout(function(){d.currItem&&d.currItem.loading?(!d.allowProgressiveImg()||d.currItem.img&&!d.currItem.img.naturalWidth)&&B(!1):B(!0)},d.options.loadingIndicatorDelay)}),k("imageLoadComplete",function(c,k){d.currItem===k&&B(!0)}))};p.setIdle=function(d){M=d;f[(d?"add":"remove")+"Class"](h,"pswp__ui--idle")};p.update=function(){g&&d.currItem?(p.updateIndexIndicator(),d.options.captionEl&&(d.options.addCaptionHTMLFn(d.currItem,y),d.currItem.title?f.removeClass(y,"pswp__caption--empty"):
f.addClass(y,"pswp__caption--empty")),oa=!0):oa=!1};p.updateFullscreen=function(){f[(c.isFullscreen()?"add":"remove")+"Class"](d.template,"pswp--fs")};p.updateIndexIndicator=function(){d.options.counterEl&&(ea.innerHTML=d.getCurrentIndex()+1+d.options.indexIndicatorSep+d.options.getNumItemsFn())};p.onGlobalTap=function(c){c=c||window.event;var h=c.target||c.srcElement;S||(c.detail&&"mouse"===c.detail.pointerType?(T(h)&&d.close(),f.hasClass(h,"pswp__img")&&(1===d.getZoomLevel()&&d.getZoomLevel()<=
d.currItem.fitRatio?d.close():d.toggleDesktopZoom(c.detail.releasePoint))):(d.options.tapToToggleControls&&(g?p.hideControls():p.showControls()),d.options.tapToClose&&(f.hasClass(h,"pswp__img")||T(h))&&d.close()))};p.onMouseOver=function(d){d=d||window.event;T(d.target||d.srcElement)?f.addClass(h,"pswp__ui--over-close"):f.removeClass(h,"pswp__ui--over-close")};p.hideControls=function(){f.addClass(h,"pswp__ui--hidden");g=!1};p.showControls=function(){g=!0;oa||p.update();f.removeClass(h,"pswp__ui--hidden")};
p.supportsFullscreen=function(){var d=document;return!!(d.exitFullscreen||d.mozCancelFullScreen||d.webkitExitFullscreen||d.msExitFullscreen)};p.getFullscreenAPI=function(){var c=document.documentElement,f;c.requestFullscreen?f={enterK:"requestFullscreen",exitK:"exitFullscreen",elementK:"fullscreenElement",eventK:"fullscreenchange"}:c.mozRequestFullScreen?f={enterK:"mozRequestFullScreen",exitK:"mozCancelFullScreen",elementK:"mozFullScreenElement",eventK:"mozfullscreenchange"}:c.webkitRequestFullscreen?
f={enterK:"webkitRequestFullscreen",exitK:"webkitExitFullscreen",elementK:"webkitFullscreenElement",eventK:"webkitfullscreenchange"}:c.msRequestFullscreen&&(f={enterK:"msRequestFullscreen",exitK:"msExitFullscreen",elementK:"msFullscreenElement",eventK:"MSFullscreenChange"});f&&(f.enter=function(){A=d.options.closeOnScroll;d.options.closeOnScroll=!1;if("webkitRequestFullscreen"===this.enterK)d.template[this.enterK](Element.ALLOW_KEYBOARD_INPUT);else return d.template[this.enterK]()},f.exit=function(){d.options.closeOnScroll=
A;return document[this.exitK]()},f.isFullscreen=function(){return document[this.elementK]});return f}}});
(function(d){d.fn.JIGphotoSwipe=function(f){var p=this,oa=d(p[0]).closest(".justified-image-grid"),g=d.extend(!0,{},f),c=function(c){var f=[];p.filter('[rel="'+c+'"]').each(function(c){c=d(this);var g=c.find("img"),h=c.find("img").attr("alt"),p=c.attr("title"),v=c.attr("data-wh").split("x"),u="jig-overflow"==c.parent().attr("class")?c.closest(".jig-imageContainer").attr("class"):c.attr("class"),u=/(?:jig-contentID)-(\w{2})-([^\s]*)/im.exec(u),g={src:c.attr("href"),w:parseInt(v[0],10),h:parseInt(v[1],
10),msrc:g.attr("src")};null!=u&&(g.contentID=u[0]);h&&(g.title=h);p&&(g.description=p);g.el=c[0];f.push(g)});return f},h=function(c){c.preventDefault();var f=d(c.target).closest(".jig-imageContainer").attr("class"),f=/(?:jig-contentID)-(\w{2})-([^\s]*)/im.exec(f),g=d(c.target).closest("a.jig-link");c=g.attr("rel");f=null!=f?f[0]:g.attr("href");y(f,c);return!1},y=function(h,p,R){var l=c(p),y,A=!1;if(0==l.length)return!1;d.each(l,function(c,d){if("undefined"!==typeof d.contentID&&d.contentID==h||d.src==
h)return f.index=c,!1});f.galleryUID=p;f.getThumbBoundsFn=function(c){if("jig-overflow"==d(l[c].el).parent().attr("class")){var f=l[c].el.getElementsByTagName("img")[0];c=d(window).scrollTop();f=f.getBoundingClientRect();return{x:f.left,y:f.top+c,w:f.width}}return{x:d(window).width()/2,y:d(window).height()/2+d(window).scrollTop(),w:0}};f.addCaptionHTMLFn=function(c,d){var f=[];"undefined"!==typeof c.title&&f.push(c.title);"undefined"!==typeof c.description&&f.push("<small>"+c.description+"</small>");
if(0==f.length)return d.children[0].innerText="",!1;d.children[0].innerHTML=f.join("<br/>");return!0};f.shareButtons=[{id:"facebook",label:"Share on Facebook",url:"https://www.facebook.com/sharer/sharer.php?u={{facebook_url}}"},{id:"twitter",label:"Tweet",url:"https://twitter.com/intent/tweet?text={{title}}&url={{url}}"},{id:"pinterest",label:"Pin it",url:"http://www.pinterest.com/pin/create/button/?url={{url}}&media={{image_url}}&description={{description}}"},{id:"googleplus",label:"Share on Google+",
url:"https://plus.google.com/share?url={{url}}"}];"undefined"!==typeof f.allowDownload&&!0===f.allowDownload&&f.shareButtons.push({id:"download",label:"Download image",url:"{{raw_image_url}}",download:!0});if(R){if(f.showAnimationDuration=0,"undefined"==typeof g.closeOnScroll||1==g.closeOnScroll)f.closeOnScroll=!1,y=!0}else f.showAnimationDuration="undefined"==typeof g.showAnimationDuration?333:g.showAnimationDuration;p=d(l[f.index].el);"jig-overflow"==p.parent().attr("class")&&"0px"!==p.find("img").css("margin-left")&&
(A=!0);A||"undefined"!==typeof f.aspectRatioMismatch&&!0===f.aspectRatioMismatch?(f.showHideOpacity=!0,f.mainClass="hidePsPlaceholder"):(f.showHideOpacity="undefined"==typeof g.showHideOpacity?!1:g.showHideOpacity,f.mainClass="undefined"==typeof g.mainClass?"":g.mainClass);d(".pswp").removeAttr("style");d.fn.JIGphotoSwipe.gallery=new PhotoSwipe(d(".pswp")[0],PhotoSwipeUI_Default,l,f);d.fn.JIGphotoSwipe.gallery.init();1==y&&setTimeout(function(){d.fn.JIGphotoSwipe.gallery.options.closeOnScroll=!0},
2E3)};(function(){oa.off("click.photoswipe").on("click.photoswipe","a.jig-link",h);var c="",d,f=location.hash,f=f.replace("%5B","["),f=f.replace("%5D","]"),f=f.replace(/([^|])(poster=|videoplayer)/mg,"$1|$2");d=f.match(/^#!([\w\-[\]]+?\/(?:(\d+)(?=\/))?(https?:\/\/[^&]*)?([A-Z]{2}\/[_\w]*)?)/im);null!==d&&(c=d[1],c=c.substring(c.indexOf("/")+1,c.length),/^([A-Z]{2}\/[_\w]*)$/im.test(c)&&(c=c.replace("/","-")));c="jig-contentID-"+c;(f=f.substring(2,f.indexOf("/")))&&c&&y(c,f,!0)})()}})(jQuery);